name: model-Titanic
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python plot_permutation_importance.py
          
          echo "## MODEL METRICS" > report.md
          cat Accuracy.txt >> report.md
          
          echo "## plot" >> report.md
          cml-publish Random_Forest_Feature_Importances.png --md >> report.md
          cml-publish Permutation_importance_low_cardinality_feature.png --md >> report.md
          cml-publish Permutation_importance_high_cardinality_feature.png --md >> report.md
          
          cml-send-comment report.md
